### ISSUE TITLE
No :id parameter given for User.instantiate

### ISSUE THREAD

**Issue by joshsmith** [tkadauke/motion-resource#19]
I'm getting the following error: 

``` zsh
Terminating app due to uncaught exception 'ArgumentError', reason: 'base.rb:27:in `instantiate:': No :id parameter given for User.instantiate (ArgumentError)`
```

Here's the `User`:

``` ruby
class User < MotionResource::Base
  attr_accessor :id

  self.collection_url = "users"
  self.member_url = "users/:id"
  self.default_url_options = {
    :payload => {
      'token' => "#{App::Persistence['facebook_access_token']}"
    }
  }
end
```

My JSON response looks like the following:

``` json
{
  "success": true,
  "user": {
    "id": 13,
    "name": "Josh Smith",
    "email": "josh@coderly.com",
    "first_name": "Josh",
    "last_name": "Smith"
  }
}
```

Could this have something to do with not having the `id` in the root object? Am I doing something else obviously wrong?

Thanks!

**Comment by tkadauke** [comment]
Yes, the problem is that MotionResource expects JSON without a root element. So either remove that element from the server, or extend the MotionResource::Base.instantiate method to optionally accept or, preferably, auto-detect JSON with a root element. Look here:

https://github.com/tkadauke/motion-resource/blob/master/lib/motion-resource/base.rb
